[package]
name = "apcstatd"
version = "1.1.0"
authors = ["Sergey A. Lisovoy <lis0x90@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
env_logger = "0.7.1"
regex = "1.3.9"
lazy_static = "1.4.0"
paho-mqtt = "0.7.1"
clap = { version = "3.1.18", features = ["derive"] }